#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
    sleep infinity
fi

# Configure & run metube
mkdir -p /mnt/data/videos 2>/dev/null
cd /app
exec 2>&1
exec python3 /app/app/main.py