#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
    sleep infinity
fi

mkdir -p /mnt/config/transmission /mnt/data/torrent_watch 2>/dev/null

if [ ! -f "/mnt/config/transmission/settings.json" ]; then
    cp /.aria2allinoneworkdir/transmission_settings.json /mnt/config/transmission/settings.json
fi

if [ ! -f "/mnt/config/transmission/transmission_trakcer_add_auto.sh" ]; then
    cp /.aria2allinoneworkdir/transmission_tracker_add_auto.sh /mnt/config/transmission/transmission_trakcer_add_auto.sh
fi

tmp=$(mktemp)
jq '."rpc-username"="'"${USER}"'" | ."rpc-password"="'"${PASSWORD}"'"' /mnt/config/transmission/settings.json >"$tmp" && mv "$tmp" /mnt/config/transmission/settings.json

if [[ "${POST_MODE}" = "copy_remote" ]] || [[ "${POST_MODE}" = "move_remote" ]]; then
    jq '."incomplete-dir-enabled"=true | ."download-dir"="/mnt/data/finished" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=true | ."script-torrent-done-seeding-filename"="/.aria2allinoneworkdir/transmission_script.sh"' /mnt/config/transmission/settings.json >"$tmp" && mv "$tmp" /mnt/config/transmission/settings.json
elif [ "${POST_MODE}" = "copy_remote_first" ]; then
    jq '."incomplete-dir-enabled"=false | ."download-dir"="/mnt/data/downloads" | ."script-torrent-done-enabled"=true | ."script-torrent-done-seeding-enabled"=false | ."script-torrent-done-filename"="/.aria2allinoneworkdir/transmission_script.sh"' /mnt/config/transmission/settings.json >"$tmp" && mv "$tmp" /mnt/config/transmission/settings.json
elif [ "${POST_MODE}" = "move" ]; then
    jq '."incomplete-dir-enabled"=true | ."download-dir"="/mnt/data/finished" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=false' /mnt/config/transmission/settings.json >"$tmp" && mv "$tmp" /mnt/config/transmission/settings.json
elif [ "${POST_MODE}" = "dummy" ]; then
    jq '."incomplete-dir-enabled"=false | ."download-dir"="/mnt/data/downloads" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=false' /mnt/config/transmission/settings.json >"$tmp" && mv "$tmp" /mnt/config/transmission/settings.json
fi

/mnt/config/transmission/transmission_tracker-add-auto.sh &

exec 2>&1
exec transmission-daemon -f -g /mnt/config/transmission
