#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
    sleep infinity
fi

mkdir -p /mnt/config/transmission /mnt/data/torrent_watch 2>/dev/null
TR_SETTINGS="/mnt/config/transmission/settings.json"

if [ ! -f "/mnt/config/transmission/settings.json" ]; then
    cp /.aria2allinoneworkdir/transmission_settings.json ${TR_SETTINGS}
fi

tmp=$(mktemp)
jq '."rpc-username"="'"${USER}"'" | ."rpc-password"="'"${PASSWORD}"'"' ${TR_SETTINGS} >"$tmp" && mv "$tmp" ${TR_SETTINGS}
export CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"

if [ "${POST_MODE}" = "copy_remote_first" ]; then
    jq '."incomplete-dir-enabled"=false | ."download-dir"="/mnt/data/downloads" | ."script-torrent-done-enabled"=true | ."script-torrent-done-seeding-enabled"=false | ."script-torrent-done-filename"="/.aria2allinoneworkdir/transmission_script.sh"' ${TR_SETTINGS} >"$tmp" && mv "$tmp" ${TR_SETTINGS}
elif [[ "${POST_MODE}" =~ "remote" ]]; then
    jq '."incomplete-dir-enabled"=false | ."download-dir"="/mnt/data/downloads" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=true | ."script-torrent-done-seeding-filename"="/.aria2allinoneworkdir/transmission_script.sh"' ${TR_SETTINGS} >"$tmp" && mv "$tmp" ${TR_SETTINGS}
elif [ "${POST_MODE}" = "move" ]; then
    jq '."incomplete-dir-enabled"=true | ."download-dir"="/mnt/data/finished" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=false' ${TR_SETTINGS} >"$tmp" && mv "$tmp" ${TR_SETTINGS}
elif [ "${POST_MODE}" = "dummy" ]; then
    jq '."incomplete-dir-enabled"=false | ."download-dir"="/mnt/data/downloads" | ."script-torrent-done-enabled"=false | ."script-torrent-done-seeding-enabled"=false' ${TR_SETTINGS} >"$tmp" && mv "$tmp" ${TR_SETTINGS}
fi

exec 2>&1
exec transmission-daemon -f -g /mnt/config/transmission
