#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
	sleep infinity
fi

# Run rclone
htpasswd -csb /.aria2allinoneworkdir/htpasswd ${USER} ${PASSWORD}
exec 2>&1
exec rclone rcd --rc-serve \
--rc-web-gui-no-open-browser \
--rc-htpasswd=/.aria2allinoneworkdir/htpasswd \
--rc-addr=localhost:56802 \
--buffer-size 4M \
--transfers ${RCLONE_TRANSFERS} \
--config /mnt/config/rclone.conf \
--rc-allow-origin=* \
--use-mmap \
--copy-links \
--exclude /.aria2allinoneworkdir/
