#!/bin/sh

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
       sleep infinity
fi

# Configure aria2
if [ ! -d "/mnt/config/aria2" ]; then
       mkdir -p /mnt/config/aria2
       cp /.aria2allinoneworkdir/aria2/*.conf /mnt/config/aria2/
       cp /.aria2allinoneworkdir/aria2/*.dat /mnt/config/aria2/
       cp /.aria2allinoneworkdir/aria2/tracker.sh /mnt/config/aria2/
fi

if [ ! -f "/mnt/config/aria2/aria2.session" ]; then
       touch /mnt/config/aria2/aria2.session
fi

cp /mnt/config/aria2/aria2_${LANGUAGE}.conf /.aria2allinoneworkdir/aria2.conf
sed -i "s|^rpc-secret=.*|rpc-secret=${PASSWORD}|g" /.aria2allinoneworkdir/aria2.conf

if [ "${ARIA_IPV6}" = "true" ]; then
       sed -i "s|^disable-ipv6=.*|disable-ipv6=false|g" /.aria2allinoneworkdir/aria2.conf
       sed -i "s|^enable-dht6=.*|enable-dht6=true|g" /.aria2allinoneworkdir/aria2.conf
else
       sed -i "s|^disable-ipv6=.*|disable-ipv6=true|g" /.aria2allinoneworkdir/aria2.conf
       sed -i "s|^enable-dht6=.*|enable-dht6=false|g" /.aria2allinoneworkdir/aria2.conf
fi

if [ "${AUTO_DRIVE_NAME}" = "true" ]; then
       DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/config/rclone.conf | sed "s/\[//g" | sed "s/\]//g")"
       sed -i "s|^drive-name=.*|drive-name=${DRIVE_NAME_AUTO}|g" /mnt/config/aria2/script.conf
fi

if [ "${POST_MODE}" = "copy_remote_first" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/"${POST_MODE}".sh|g" /.aria2allinoneworkdir/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/copy_remote_other.sh|g" /.aria2allinoneworkdir/aria2.conf
elif [ "${POST_MODE}" = "dummy" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /.aria2allinoneworkdir/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /.aria2allinoneworkdir/aria2.conf
elif [ "${POST_MODE}" = "custom" ]; then
       :
else
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/"${POST_MODE}".sh|g" /.aria2allinoneworkdir/aria2.conf
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /.aria2allinoneworkdir/aria2.conf
fi

if [[ "${CLEAN_UNFINISHED_FAILED_TASK_FILES}" = "true" ]] && [[ "${POST_MODE}" != "custom" ]]; then
       sed -i "s|^on-download-stop=/.aria2allinoneworkdir/aria2/.*.sh|on-download-stop=/.aria2allinoneworkdir/aria2/delete.sh|g" /.aria2allinoneworkdir/aria2.conf
elif [ "${POST_MODE}" = "custom" ]; then
       :
else
       sed -i "s|^on-download-stop=/.aria2allinoneworkdir/aria2/.*.sh|on-download-stop=/.aria2allinoneworkdir/aria2/clean.sh|g" /.aria2allinoneworkdir/aria2.conf
fi

# Run aria2
exec 2>&1
exec aria2c --conf-path="/.aria2allinoneworkdir/aria2.conf" \
--enable-rpc \
--dht-listen-port=${BT_PORT} \
--listen-port=${BT_PORT} \
--rpc-listen-port=56800 \
--show-console-readout false \
--enable-mmap true
