#!/bin/sh

# Configure aria2
if [ ! -d "/mnt/config/aria2" ]; then
       mkdir -p /mnt/config/aria2
       cp /.aria2allinoneworkdir/aria2/aria2_${LANGUAGE}.conf /mnt/config/aria2/aria2.conf
       cp /.aria2allinoneworkdir/aria2/*.dat /mnt/config/aria2/
       cp /.aria2allinoneworkdir/aria2/tracker.sh /mnt/config/aria2/
       cp /.aria2allinoneworkdir/aria2/script.conf /mnt/config/aria2/script.conf
fi

if [ ! -f "/mnt/config/aria2/aria2.session" ]; then
       touch /mnt/config/aria2/aria2.session
fi

if [ "${ARIA_IPV6}" = "true" ]; then
       sed -i "s|^disable-ipv6=.*|disable-ipv6=false|g" /mnt/config/aria2/aria2.conf
       sed -i "s|^enable-dht6=.*|enable-dht6=true|g" /mnt/config/aria2/aria2.conf
else
       sed -i "s|^disable-ipv6=.*|disable-ipv6=true|g" /mnt/config/aria2/aria2.conf
       sed -i "s|^enable-dht6=.*|enable-dht6=false|g" /mnt/config/aria2/aria2.conf
fi

if [ "${AUTO_DRIVE_NAME}" = "true" ]; then
       DRIVE_NAME_AUTO="$(sed -n '1p' /mnt/config/rclone.conf | sed "s/\[//g" | sed "s/\]//g")"
       sed -i "s|^drive-name=.*|drive-name=${DRIVE_NAME_AUTO}|g" /mnt/config/aria2/script.conf
fi

if [ "${POST_MODE}" = "copy_remote_first" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/"${POST_MODE}".sh|g" /mnt/config/aria2/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/copy_remote_other.sh|g" /mnt/config/aria2/aria2.conf
elif [ "${POST_MODE}" = "dummy" ]; then
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/config/aria2/aria2.conf
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/config/aria2/aria2.conf
elif [ "${POST_MODE}" = "custom" ]; then
       :
else
       sed -i "s|^on-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-download-complete=/.aria2allinoneworkdir/aria2/"${POST_MODE}".sh|g" /mnt/config/aria2/aria2.conf
       sed -i "s|^on-bt-download-complete=/.aria2allinoneworkdir/aria2/.*.sh|on-bt-download-complete=/.aria2allinoneworkdir/aria2/clean.sh|g" /mnt/config/aria2/aria2.conf
fi

# Run aria2
exec 2>&1
exec aria2c --conf-path="/mnt/config/aria2/aria2.conf" \
--enable-rpc \
--rpc-secret=${PASSWORD} \
--rpc-listen-port=56800
